component: koa
name: koaDemo
app: appDemo

inputs:
  entryFile: sls.js
  src: ./
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
